class androidx.loader.content.ModernAsyncTask$3 extends java.util.concurrent.FutureTask
{
    final androidx.loader.content.ModernAsyncTask this$0;

    void <init>(androidx.loader.content.ModernAsyncTask, java.util.concurrent.Callable)
    {
        java.util.concurrent.Callable r2;
        androidx.loader.content.ModernAsyncTask $r1;
        androidx.loader.content.ModernAsyncTask$3 r0;

        r0 := @this;

        $r1 := @parameter0;

        r2 := @parameter1;

        r0.this$0 = $r1;

        specialinvoke r0.<init>(r2);

        return;
    }

    protected void done()
    {
        java.lang.Throwable r3;
        java.util.concurrent.CancellationException r5;
        java.lang.RuntimeException $r4;
        androidx.loader.content.ModernAsyncTask $r2;
        androidx.loader.content.ModernAsyncTask$3 r0;
        java.util.concurrent.ExecutionException r6;
        java.lang.InterruptedException r7;
        java.lang.Object $r1;

        r0 := @this;

     label1:
        $r1 = virtualinvoke r0.get();

     label2:
        $r2 = r0.this$0;

     label3:
        virtualinvoke $r2.postResultIfNotInvoked($r1);

     label4:
        goto label9;

     label5:
        r3 := @caughtexception;

        $r4 = new java.lang.RuntimeException;

        specialinvoke $r4.<init>("An error occurred while executing doInBackground()", r3);

        throw $r4;

     label6:
        r5 := @caughtexception;

        $r2 = r0.this$0;

        virtualinvoke $r2.postResultIfNotInvoked(null);

        goto label9;

     label7:
        r6 := @caughtexception;

        $r4 = new java.lang.RuntimeException;

        r3 = virtualinvoke r6.getCause();

        specialinvoke $r4.<init>("An error occurred while executing doInBackground()", r3);

        throw $r4;

     label8:
        r7 := @caughtexception;

        android.util.Log.w("AsyncTask", r7);

     label9:
        return;

        catch java.lang.InterruptedException from label1 to label2 with label8;
        catch java.lang.InterruptedException from label3 to label4 with label8;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label7;
        catch java.util.concurrent.ExecutionException from label3 to label4 with label7;
        catch java.util.concurrent.CancellationException from label1 to label2 with label6;
        catch java.util.concurrent.CancellationException from label3 to label4 with label6;
        catch java.lang.Throwable from label1 to label4 with label5;
    }
}
